.TH MKMEDIA 1
.SH NAME
mkmedia \- create Windows 10 installation trees
.SH SYNOPSIS
.B mkmedia
\fIESD_PATH \fIMEDIA_PATH
.SH DESCRIPTION
.B mkmedia
creates a Windows 10 installation tree from an ESD
(electronic software delivery) image
.SH EXIT CODE
If an error occurs \fBmkmedia \fRexits with 1 and prints an error message, if no error occurs the exit code is 0
